apps/artemis-web-e2e/src/integration/app.spec.ts
apps/artemis-web-e2e/src/support/commands.ts
apps/artemis-web/components/bgptable/bgptable.tsx
apps/artemis-web/components/header/header.tsx
apps/artemis-web/components/layout/layout.tsx
apps/artemis-web/components/ongoing-hijack-table/ongoing-hijack-table.tsx
apps/artemis-web/pages/_app.tsx
apps/artemis-web/pages/api/users.ts
apps/artemis-web/pages/bgpupdates.tsx
apps/artemis-web/pages/hijacks.tsx
apps/artemis-web/pages/index.tsx
apps/artemis-web/pages/overview.tsx
apps/artemis-web/pages/signin.tsx
apps/artemis-web/pages/signup.tsx
apps/artemis-web/specs/index.spec.tsx
apps/artemis-web/utils/graphql.ts
package.json

add extra graphql queries + fixed tests + fix Replace process.browser issue

Graphql api

---

apps/artemis-web-e2e/src/integration/app.spec.ts
apps/artemis-web/lib/passport.ts
apps/artemis-web/pages/api/users.ts
package.json
yarn.lock

fix: replace the less secure bcrypt with argon2

---

apps/artemis-web/components/404-hoc/404-hoc.tsx
apps/artemis-web/components/header/header.tsx
apps/artemis-web/lib/helpers.ts
apps/artemis-web/pages/adminpanel.tsx
apps/artemis-web/pages/bgpupdates.tsx
apps/artemis-web/pages/hijacks.tsx
apps/artemis-web/pages/overview.tsx
apps/artemis-web/pages/pending.tsx
apps/artemis-web/tsconfig.json

feat: custom 404 message when there is a lack of permission

---

apps/artemis-web-e2e/src/integration/app.spec.ts
apps/artemis-web-e2e/src/support/commands.ts
apps/artemis-web/components/header/header.tsx
apps/artemis-web/components/password-change/password-change.tsx
apps/artemis-web/pages/api/auth/change-password.ts

Adds password change functionality

feat: password change functionality

---

apps/artemis-web/components/bgp-table/bgp-table.tsx
apps/artemis-web/components/hijack-table/hijack-table.tsx
apps/artemis-web/components/module-state/module-state.spec.tsx
apps/artemis-web/components/module-state/module-state.tsx
apps/artemis-web/components/ongoing-hijack-table/ongoing-hijack-table.tsx
apps/artemis-web/components/status-table/status-table.tsx
apps/artemis-web/components/system-module/system-module.tsx
apps/artemis-web/components/tooltip/tooltip.tsx
apps/artemis-web/context/tooltip-context.ts
apps/artemis-web/libs/graphql.ts
apps/artemis-web/pages/_app.tsx
apps/artemis-web/pages/admin/system.tsx
apps/artemis-web/pages/bgpupdates.tsx
apps/artemis-web/pages/hijack.tsx
apps/artemis-web/pages/hijacks.tsx
apps/artemis-web/utils/fetch-data.ts
apps/artemis-web/utils/hooks/use-graphql.ts
apps/artemis-web/utils/parsers.tsx

feat: tooltips fetch on hover only + share tooltip state with context

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

feat: issue templates

---

apps/artemis-web/libs/graphql.ts
apps/artemis-web/public/mockServiceWorker.js

fix: bgp service + as_path filters

---

.github/workflows/dockerhub.yml
apps/artemis-web/components/bgp-table/bgp-table.tsx
apps/artemis-web/components/hijack-info/hijack-info.tsx
apps/artemis-web/components/hijack-table/hijack-table.tsx
apps/artemis-web/components/learn-rule/learn-rule.tsx
apps/artemis-web/components/ongoing-hijack-table/ongoing-hijack-table.tsx
apps/artemis-web/pages/api/hijack.ts
apps/artemis-web/pages/hijack.tsx
apps/artemis-web/pages/hijacks.tsx
apps/artemis-web/pages/styles.css

Fix actions

---

apps/artemis-web/utils/fetch-data.ts

fix: unmitigate bug

---

docs/pull_request_template.md

feat: pr template

---

apps/artemis-web/components/bgp-table/bgp-table.tsx
apps/artemis-web/components/hijack-table/hijack-table.tsx
apps/artemis-web/components/ongoing-hijack-table/ongoing-hijack-table.tsx
apps/artemis-web/libs/graphql.ts
apps/artemis-web/pages/hijack.tsx
apps/artemis-web/pages/hijacks.tsx
apps/artemis-web/utils/token.tsx

fix: multiple filters + pagination bug

---

.env
apps/artemis-web-e2e/src/integration/app2.spec.ts
apps/artemis-web/libs/passport-strategies/ldap-strategy.ts
apps/artemis-web/utils/parsers.tsx

Ldap fixes

---

apps/artemis-web/pages/_app.tsx
apps/artemis-web/pages/admin/system.tsx
apps/artemis-web/pages/admin/user_management.tsx
apps/artemis-web/pages/bgpupdates.tsx
apps/artemis-web/pages/config_comparison.tsx
apps/artemis-web/pages/dashboard.tsx
apps/artemis-web/pages/hijack.tsx
apps/artemis-web/pages/hijacks.tsx
apps/artemis-web/pages/password_change.tsx
apps/artemis-web/pages/pending.tsx
apps/artemis-web/utils/token.tsx

Fixing the alert popup showin up multiple times
Resolves #
>)`>>>)>

Logout alerts

---

apps/artemis-web/components/bgp-table/bgp-table.tsx
apps/artemis-web/components/config-comparison/config-comparison.tsx
apps/artemis-web/components/dataplane-table/dataplane-table.tsx
apps/artemis-web/components/hijack-table/hijack-table.tsx
apps/artemis-web/components/module-state/module-state.tsx
apps/artemis-web/components/ongoing-hijack-table/ongoing-hijack-table.tsx
apps/artemis-web/components/system-configuration/system-configuration.tsx
apps/artemis-web/pages/admin/user_management.tsx
apps/artemis-web/utils/parsers.tsx
apps/artemis-web/utils/token.tsx

Fix the timestamp issue (timezones). 
Resolves #103 
Resolves #
>)`>>>)>

Timestamps fix

---

.env

minor in ldap conf

---

apps/artemis-web/components/hijack-info/hijack-info.tsx
apps/artemis-web/components/hijack-table/hijack-table.tsx
apps/artemis-web/libs/graphql.ts
apps/artemis-web/pages/api/hijack.ts
apps/artemis-web/pages/api/rmq_action.ts
apps/artemis-web/pages/api/rmq_admin_action.ts
apps/artemis-web/pages/hijack.tsx
apps/artemis-web/utils/fetch-data.ts

Resolves #98 
Added notification in the hijack page + disabled the display of the actions the user does not has access to. 
Resolves #
>)`>>>)>

401 notification

---

.gitpod.Dockerfile
.gitpod.yml
apps/artemis-web-e2e/src/integration/app.spec.ts
apps/artemis-web/pages/api/auth/signup.ts
apps/artemis-web/pages/pending.tsx

Resolves #117 
Resolves #117
>)`>>>)>

fix pending user

---

docs/changelog.md

Changelog updates

---

apps/artemis-web/Dockerfile
apps/artemis-web/scripts/query.js

Fix the mongo db user bug
Resolves #
>)`>>>)>

fix: mongo bugfix

---

apps/artemis-web/scripts/query.js

small mongo client fix

---

apps/artemis-web/components/401-hoc/401-hoc.tsx
apps/artemis-web/components/desktop-header/desktop-header.tsx
apps/artemis-web/components/mobile-header/mobile-header.tsx
apps/artemis-web/pages/password_change.tsx
apps/artemis-web/utils/parsers.tsx

hide password change page for ldap users
Resolves #
>)`>>>)>

fix: hide password change for ldap users

---

apps/artemis-web-e2e/src/integration/ldap.spec.ts
apps/artemis-web-e2e/src/integration/visual.spec.ts
apps/artemis-web/components/login/login.spec.tsx
apps/artemis-web/components/login/login.tsx
apps/artemis-web/pages/api/ldap_ping.ts
package.json
yarn.lock

fix: LDAP button is hidden when no LDAP service is being used

---

apps/artemis-web/libs/passport-strategies/google-strategy.ts

A minor fix to avoid app crashing when the google client id is undefined.
- [] Front-End (React.js)
- [] Build System
Resolves #
>)`>>>)>

fix: google cid empty check

---

apps/artemis-web/components/hijack-table/hijack-table.tsx
apps/artemis-web/components/ongoing-hijack-table/ongoing-hijack-table.tsx
yarn.lock

Fixing the web app crash when the type filter is used,
Resolves #
>)`>>>)>

fix: type field validation

---

apps/artemis-web/components/ongoing-hijack-table/ongoing-hijack-table.tsx
apps/artemis-web/scripts/entrypoint
apps/artemis-web/utils/hooks/use-graphql.ts

Pre release fixes
